server:
  port: 8080

logging:
  level: 
    learning: trace

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/fss
    username: root
    password: "012315"
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类所做包
  type-aliases-package: com.cq.model
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml